# Generated by Django 6.1 on 2026-08-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Yadotena Milk & Foods', max_length=200)),
                ('phone', models.CharField(default='+251 91 123 4567', max_length=50)),
                ('address', models.CharField(default='Bole Road, Addis Ababa', max_length=255)),
                ('service_charge_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('guest_wifi_ssid', models.CharField(default='Yadotena_Milk_5G', max_length=100)),
                ('guest_wifi_password', models.CharField(default='Yadotena2026', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant Setting',
                'verbose_name_plural': 'Restaurant Settings',
            },
        ),
    ]
