-- Migration 000004: Fix schema column types for service_requests, expenses, and legacy tables

ALTER TABLE IF EXISTS service_requests ALTER COLUMN id TYPE VARCHAR(50);
ALTER TABLE IF EXISTS service_requests ALTER COLUMN table_id TYPE VARCHAR(50);

ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS date DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS receipt_url TEXT;
ALTER TABLE IF EXISTS expenses ALTER COLUMN id TYPE VARCHAR(50);

ALTER TABLE IF EXISTS dining_sessions ALTER COLUMN table_id TYPE VARCHAR(50);
ALTER TABLE IF EXISTS customers ALTER COLUMN id TYPE VARCHAR(50);
ALTER TABLE IF EXISTS reviews ALTER COLUMN id TYPE VARCHAR(50);
