# Generated by Django 6.1 on 2026-08-08 22:28

import apps.expenses.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(default=apps.expenses.models.generate_expense_id, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Dairy Supplies', 'Dairy & Milk Supplies'), ('Kitchen Supplies', 'Kitchen & Food Supplies'), ('Packaging', 'Packaging & Takeaway'), ('Utilities', 'Utilities (Power, Water, Gas)'), ('Maintenance', 'Maintenance & Repairs'), ('Salaries', 'Staff Salaries'), ('Transportation', 'Transportation & Logistics'), ('Other', 'Other Expenses')], default='Dairy Supplies', max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(default='Cash', max_length=50)),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
