# Generated by Django 6.1 on 2026-08-08 22:28

import apps.service_requests.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.CharField(default=apps.service_requests.models.generate_request_id, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WAITER', 'Call Waiter'), ('BILL', 'Request Bill'), ('ASSISTANCE', 'Special Assistance')], default='WAITER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='tables.table')),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
