# Generated by Django 6.1 on 2026-08-08 22:28

import apps.tables.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('ORDERING', 'Ordering'), ('PREPARING', 'Preparing Food'), ('WAITING_FOR_SERVICE', 'Waiting for Service'), ('WAITING_FOR_PAYMENT', 'Waiting for Payment'), ('CLEANING', 'Cleaning Required')], default='AVAILABLE', max_length=30)),
                ('qr_token', models.CharField(default=apps.tables.models.generate_qr_token, max_length=100, unique=True)),
                ('current_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BILLED', 'Billed'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tables.table')),
            ],
            options={
                'verbose_name': 'Dining Session',
                'verbose_name_plural': 'Dining Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
